refractor trip database

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -18,63 +18,87 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3
 
-
       - name: Set Up keys
         run: |
-          mkdir -p src/assets/keys 
+          mkdir -p src/assets/keys
           echo "${{ secrets.PRIVATE_KEY }}" > src/assets/keys/private.pem
           echo "${{ secrets.PUBLIC_KEY }}" > src/assets/keys/public.pem
 
       - name: Set up env
         run: |
-          echo "TEST_USER=TestUser" >> .env.test
-          echo "TEST_PASS=Testpass11234@" >> .env.test
-          echo "INVALID_ACCESS_JWT=${{ secrets.INVALID_ACCESS_JWT }}" >> .env.test
-          echo "AQI_API_KEY=${{ secrets.AQI_API_KEY }}" >> .env.test
-          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env.test
-          echo "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}" >> .env.test
-          echo "AWS_LOG_BUCKET=${{ secrets.AWS_LOG_BUCKET }}" >> .env.test
-          echo "AWS_MEDIA_BUCKET=${{ secrets.AWS_MEDIA_BUCKET }}" >> .env.test
-          echo "AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }}" >> .env.test
-          echo "AWS_S3_LOGS_BUCKET=${{ secrets.AWS_S3_LOGS_BUCKET }}" >> .env.test
-          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env.test
-          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env.test
-          echo "DATABASE_URL=postgresql://testuser:testpass@test_db:5432/tripin" >> .env.test
-          echo "DB_HOST=test_db" >> .env.test
-          echo "DB_NAME=tripin" >> .env.test
-          echo "DB_PASS=testpass" >> .env.test
-          echo "DB_PORT=5432" >> .env.test
-          echo "DB_USER=testuser" >> .env.test
-          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env.test
-          echo "EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}" >> .env.test
-          echo "ENV_PATH=${{ secrets.ENV_PATH }}" >> .env.test
-          echo "EXPIRED_ACCESS_JWT=${{ secrets.EXPIRED_ACCESS_JWT }}" >> .env.test
-          echo "EXPIRED_REFRESH_JWT=${{ secrets.EXPIRED_REFRESH_JWT }}" >> .env.test
-          echo "INVALID_REFRESH_JWT=${{ secrets.INVALID_REFRESH_JWT }}" >> .env.test
-          echo "MAIL_DEFAULT_SENDER=${{ secrets.MAIL_DEFAULT_SENDER }}" >> .env.test
-          echo "MAPBOX_PUBLIC_KEY=${{ secrets.MAPBOX_PUBLIC_KEY }}" >> .env.test
-          echo "PRIVATE_KEY_PATH=src/assets/keys/private.pem" >> .env.test
-          echo "PUBLIC_KEY_PATH=src/assets/keys/public.pem" >> .env.test
-          echo "REDIS_HOST=test_redis" >> .env.test
-          echo "REDIS_PORT=6379" >> .env.test
-          echo "REDIS_URL=redis://test_redis" >> .env.test
-          echo "SOCKET_HOST=127.0.0.1" >> .env.test
-          echo "SOCKET_PORT=12345" >> .env.test
-          echo "TEST_TRIP_NAME=Tedddd2s32" >> .env.test
-          echo "VPS_HOST=${{ secrets.VPS_HOST }}" >> .env.test
-          echo "VPS_SSH_KEY=${{ secrets.VPS_SSH_KEY }}" >> .env.test
-          echo "VPS_USERNAME=${{ secrets.VPS_USERNAME }}" >> .env.test
-  
+          echo "TEST_USER=TestUser" >> .env
+          echo "TEST_PASS=Testpass11234@" >> .env
+          echo "INVALID_ACCESS_JWT=${{ secrets.INVALID_ACCESS_JWT }}" >> .env
+          echo "AQI_API_KEY=${{ secrets.AQI_API_KEY }}" >> .env
+          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
+          echo "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}" >> .env
+          echo "AWS_LOG_BUCKET=${{ secrets.AWS_LOG_BUCKET }}" >> .env
+          echo "AWS_MEDIA_BUCKET=${{ secrets.AWS_MEDIA_BUCKET }}" >> .env
+          echo "AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }}" >> .env
+          echo "AWS_S3_LOGS_BUCKET=${{ secrets.AWS_S3_LOGS_BUCKET }}" >> .env
+          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
+          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
+          echo "DATABASE_URL=postgresql://testuser:testpass@localhost:8995/tripin" >> .env
+          echo "DB_HOST=localhost" >> .env
+          echo "DB_NAME=tripin" >> .env
+          echo "DB_PASS=testpass" >> .env
+          echo "DB_PORT=5435" >> .env
+          echo "DB_USER=testuser" >> .env
+          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env
+          echo "EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}" >> .env
+          echo "ENV_PATH=${{ secrets.ENV_PATH }}" >> .env
+          echo "EXPIRED_ACCESS_JWT=${{ secrets.EXPIRED_ACCESS_JWT }}" >> .env
+          echo "EXPIRED_REFRESH_JWT=${{ secrets.EXPIRED_REFRESH_JWT }}" >> .env
+          echo "INVALID_REFRESH_JWT=${{ secrets.INVALID_REFRESH_JWT }}" >> .env
+          echo "MAIL_DEFAULT_SENDER=${{ secrets.MAIL_DEFAULT_SENDER }}" >> .env
+          echo "MAPBOX_PUBLIC_KEY=${{ secrets.MAPBOX_PUBLIC_KEY }}" >> .env
+          echo "PRIVATE_KEY_PATH=src/assets/keys/private.pem" >> .env
+          echo "PUBLIC_KEY_PATH=src/assets/keys/public.pem" >> .env
+          echo "REDIS_HOST=localhost" >> .env
+          echo "REDIS_PORT=8995" >> .env
+          echo "REDIS_URL=redis://localhost" >> .env
+          echo "SOCKET_HOST=127.0.0.1" >> .env
+          echo "SOCKET_PORT=12345" >> .env
+          echo "TEST_TRIP_NAME=Tedddd2s32" >> .env
+          echo "VPS_HOST=${{ secrets.VPS_HOST }}" >> .env
+          echo "VPS_SSH_KEY=${{ secrets.VPS_SSH_KEY }}" >> .env
+          echo "VPS_USERNAME=${{ secrets.VPS_USERNAME }}" >> .env
 
-      
       - name: Set Up and Run Tests
         run: |
-          docker rm -f test_tripin_db test_tripin_redis test_tripin_server_test 2>/dev/null || true
+          docker rm -f test_tripin_db test_tripin_redis 2>/dev/null || true
           docker compose -f docker-compose.test.yml down -v --remove-orphans
-          sleep 3
-          docker compose -f docker-compose.test.yml --env-file .env.test up \
-          --build \
-          --abort-on-container-exit 2>&1 | less
+
+          sudo apt-get update && \
+          sudo apt-get install -y gcc libpq-dev python3-dev && \
+          sudo rm -rf /var/lib/apt/lists/*
+
+          docker compose -f docker-compose.test.yml --env-file .env up -d
+
+          echo "Waiting for postgres..."
+          until docker exec test_tripin_db pg_isready -U testuser -d tripin; do
+            sleep 1
+          done
+
+          echo "Waiting for redis..."
+          until docker exec test_tripin_redis redis-cli ping; do
+            sleep 1
+          done
+
+          echo "Set Up Enviroment..."
+          python3 -m venv .venv
+          source .venv/bin/activate
+          pip install --no-cache-dir -r requirements.txt
+
+          echo "Migration..."
+          alembic upgrade head
+
+          echo "Create test user..."
+          until python scripts/create_test_user.py; do
+            sleep 1
+          done
+          echo "Run Test..."
+          python -m pytest tests/ -v
 
       - name: Clean Up
         if: always()
